# Generated by Django 4.0.5 on 2022-06-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_categoria_idcategoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(max_length=6, primary_key=True, serialize=False)),
                ('nom_producto', models.CharField(max_length=40)),
                ('stock', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('img_producto', models.ImageField(null=True, upload_to='static/core/img')),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id_promocion', models.IntegerField(max_length=6, primary_key=True, serialize=False)),
                ('nom_promocion', models.CharField(max_length=40)),
                ('porcentaje', models.IntegerField(max_length=4)),
                ('fecha_ini', models.DateTimeField()),
                ('fecha_termino', models.DateTimeField()),
            ],
        ),
    ]
