# Generated by Django 4.0.5 on 2022-07-03 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_nuevousuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='img_producto',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
