# Generated by Django 4.0.5 on 2022-07-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_producto_img_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevousuario',
            name='suscrito',
            field=models.BooleanField(default=False),
        ),
    ]
